//
// NewsDataSources.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NewsDataSources: Codable {

    public var status: String?
    public var results: [NewsDataSource]?

    public init(status: String? = nil, results: [NewsDataSource]? = nil) {
        self.status = status
        self.results = results
    }


}
