//
// NewsDataSourcesResults.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct NewsDataSource: Codable, Identifiable {

    public var id = UUID()

    public var _id: String?
    public var name: String?
    public var url: String?
    public var _description: String?
    public var category: [String]?
    public var language: [String]?
    public var country: [String]?

    public init(_id: String? = nil, name: String? = nil, url: String? = nil, _description: String? = nil, category: [String]? = nil, language: [String]? = nil, country: [String]? = nil) {
        self._id = _id
        self.name = name
        self.url = url
        self._description = _description
        self.category = category
        self.language = language
        self.country = country
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case name
        case url
        case _description = "description"
        case category
        case language
        case country
    }

}
