//
// SourceNewsData.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SourceNewsData: Codable {

    public var status: String?
    public var results: [SourceNewsDataResults]?

    public init(status: String? = nil, results: [SourceNewsDataResults]? = nil) {
        self.status = status
        self.results = results
    }


}
