//
// SourceNewsApi.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SourceNewsApi: Codable {

    public var status: String?
    public var sources: [SourceNewsApiSources]?

    public init(status: String? = nil, sources: [SourceNewsApiSources]? = nil) {
        self.status = status
        self.sources = sources
    }


}
