//
// DefaultAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class DefaultAPI {
    /**
     Get news list

     - parameter sources: (query)  
     - parameter page: (query)  
     - parameter pageSize: (query)  (optional, default to 25)
     - parameter apiKey: (query)  (optional, default to c74e894ef21646e28347927d57a85b87)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func newsApiResults(sources: String,
                                   page: Int,
                                   pageSize: Int? = 10,
                                   apiKey: String? = "c74e894ef21646e28347927d57a85b87",
                                   completion: @escaping ((_ data: NewsApiResults?,
                                                           _ error: Error?) -> Void)) {
        newsApiResultsWithRequestBuilder(sources: sources, page: page, pageSize: pageSize, apiKey: apiKey).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get news list
     - GET /newsapi.org/v2/everything
     - 

     - examples: [{contentType=application/json, example=[ {
  "totalResults" : 0,
  "articles" : [ {
    "publishedAt" : "2000-01-23T04:56:07.000+00:00",
    "author" : "author",
    "urlToImage" : "urlToImage",
    "description" : "description",
    "source" : {
      "name" : "name",
      "id" : "id"
    },
    "title" : "title",
    "url" : "url",
    "content" : "content"
  }, {
    "publishedAt" : "2000-01-23T04:56:07.000+00:00",
    "author" : "author",
    "urlToImage" : "urlToImage",
    "description" : "description",
    "source" : {
      "name" : "name",
      "id" : "id"
    },
    "title" : "title",
    "url" : "url",
    "content" : "content"
  } ],
  "status" : "status"
}, {
  "totalResults" : 0,
  "articles" : [ {
    "publishedAt" : "2000-01-23T04:56:07.000+00:00",
    "author" : "author",
    "urlToImage" : "urlToImage",
    "description" : "description",
    "source" : {
      "name" : "name",
      "id" : "id"
    },
    "title" : "title",
    "url" : "url",
    "content" : "content"
  }, {
    "publishedAt" : "2000-01-23T04:56:07.000+00:00",
    "author" : "author",
    "urlToImage" : "urlToImage",
    "description" : "description",
    "source" : {
      "name" : "name",
      "id" : "id"
    },
    "title" : "title",
    "url" : "url",
    "content" : "content"
  } ],
  "status" : "status"
} ]}]
     - parameter sources: (query)  
     - parameter page: (query)  
     - parameter pageSize: (query)  (optional, default to 25)
     - parameter apiKey: (query)  (optional, default to c74e894ef21646e28347927d57a85b87)

     - returns: RequestBuilder<[NewsApiResults]> 
     */
    open class func newsApiResultsWithRequestBuilder(sources: String,
                                                     page: Int,
                                                     pageSize: Int? = 10,
                                                     apiKey: String? = "c74e894ef21646e28347927d57a85b87") -> RequestBuilder<NewsApiResults> {
        let path = "/newsapi.org/v2/everything"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "sources": sources, 
                        "page": page.encodeToJSON(), 
                        "pageSize": pageSize?.encodeToJSON(), 
                        "apiKey": apiKey
        ])

        let requestBuilder: RequestBuilder<NewsApiResults>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Get news sources list

     - parameter apiKey: (query)  (optional, default to c74e894ef21646e28347927d57a85b87)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func newsApiSources(apiKey: String? = "c74e894ef21646e28347927d57a85b87",
                                   completion: @escaping ((_ data: NewsApiSources?,
                                                           _ error: Error?) -> Void)) {
        newsApiSourcesWithRequestBuilder(apiKey: apiKey).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get news sources list
     - GET /newsapi.org/v2/top-headlines/sources
     - 

     - examples: [{contentType=application/json, example=[ {
  "sources" : [ {
    "country" : "country",
    "name" : "name",
    "description" : "description",
    "language" : "language",
    "id" : "id",
    "category" : "category",
    "url" : "url"
  }, {
    "country" : "country",
    "name" : "name",
    "description" : "description",
    "language" : "language",
    "id" : "id",
    "category" : "category",
    "url" : "url"
  } ],
  "status" : "status"
}, {
  "sources" : [ {
    "country" : "country",
    "name" : "name",
    "description" : "description",
    "language" : "language",
    "id" : "id",
    "category" : "category",
    "url" : "url"
  }, {
    "country" : "country",
    "name" : "name",
    "description" : "description",
    "language" : "language",
    "id" : "id",
    "category" : "category",
    "url" : "url"
  } ],
  "status" : "status"
} ]}]
     - parameter apiKey: (query)  (optional, default to c74e894ef21646e28347927d57a85b87)

     - returns: RequestBuilder<[NewsApiSources]> 
     */
    open class func newsApiSourcesWithRequestBuilder(apiKey: String? = "c74e894ef21646e28347927d57a85b87") -> RequestBuilder<NewsApiSources> {
        let path = "/newsapi.org/v2/top-headlines/sources"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "apiKey": apiKey
        ])


        let requestBuilder: RequestBuilder<NewsApiSources>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**
     Get news sources list

     - parameter apikey: (query)  (optional, default to pub_6104174df9dc7974a0cc89668d388e41d47c)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func newsDataSources(apikey: String? = "pub_6104174df9dc7974a0cc89668d388e41d47c",
                                    completion: @escaping ((_ data: NewsDataSources?,
                                                            _ error: Error?) -> Void)) {
        newsDataSourcesWithRequestBuilder(apikey: apikey).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     Get news sources list
     - GET /newsdata.io/api/1/sources
     - 

     - examples: [{contentType=application/json, example=[ {
  "results" : [ {
    "country" : [ "country", "country" ],
    "name" : "name",
    "description" : "description",
    "language" : [ "language", "language" ],
    "id" : "id",
    "category" : [ "category", "category" ],
    "url" : "url"
  }, {
    "country" : [ "country", "country" ],
    "name" : "name",
    "description" : "description",
    "language" : [ "language", "language" ],
    "id" : "id",
    "category" : [ "category", "category" ],
    "url" : "url"
  } ],
  "status" : "status"
}, {
  "results" : [ {
    "country" : [ "country", "country" ],
    "name" : "name",
    "description" : "description",
    "language" : [ "language", "language" ],
    "id" : "id",
    "category" : [ "category", "category" ],
    "url" : "url"
  }, {
    "country" : [ "country", "country" ],
    "name" : "name",
    "description" : "description",
    "language" : [ "language", "language" ],
    "id" : "id",
    "category" : [ "category", "category" ],
    "url" : "url"
  } ],
  "status" : "status"
} ]}]
     - parameter apikey: (query)  (optional, default to pub_6104174df9dc7974a0cc89668d388e41d47c)

     - returns: RequestBuilder<[NewsDataSources]> 
     */
    open class func newsDataSourcesWithRequestBuilder(apikey: String? = "pub_6104174df9dc7974a0cc89668d388e41d47c") -> RequestBuilder<NewsDataSources> {
        let path = "/newsdata.io/api/1/sources"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        var url = URLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems([
                        "apikey": apikey
        ])

        let requestBuilder: RequestBuilder<NewsDataSources>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
}
